rescaling_factor_kinetic_loss:
  value: 1000
  
segmentation_list:
  value: ["liver"]
  #value: ["brain", "liver"]
  #value: ["brain", "liver", "pancreas"]
  #value: ["brain", "liver", "pancreas", "lung"]
  #value: ["brain", "liver", "pancreas", "lung", "heart"]

batch_size: 
  value: 1

reduce_monitor:
  value: "val_loss"
