modality: 
  value: "sweep" # "test", "train", "sweep"

# Architecture
use_spatio_temporal_unet: #Convolution:: true -> Spatio-temporal, false -> 3D
  value: True

model_depth:
  value: 4

max_pool_time: #Pooling:: true -> 3D, false -> Space
  value: True

final_activation: #Final activation:: multi_clamp, clamp, absolute
  value: "multi_clamp" 

activation:
  value:  "ELU"

bounding_box:
  value: False

patch_size: #Just working as a dataset specifier
  value: 128

  # P512: Full Volume per slices
  # P128: Full Volume per slices without empty slices
  
# Dataset
patient_list:
  value:  {
          #DONE: Use debugging training list for sweep
          #"train": ["01", "07", "06", "10", "15", "19", "21", "23", "27", "29"],
          "train": ["01", "07"],
          #"validation": ["14", "16", "17", "18"], #DONE: remove 01 from validation because there is not batch = 5 anymore
          "validation": ["14", "16", "17"],
          "test": ["28", "28", "08", "09", "20", "24", "25", "26", "03"]
        }

slices_per_patient_train:         # Should be "None" or "all" if all the slices must be included
  value: "all"

slices_per_patient_val:
  value: "all"

slices_per_patient_test:
  value: "all"

# Training options
epochs: 
  value: 20

continue_checkpoint:
  value: ""

batch_norm: 
  desc: Use of batch normalization
  value: False

learning_rate:
  value: 0.0001 

batch_size: 
  value: 1

lr_scheduler:
  value: "CosineAnnealingLR" # Options: CosineAnnealingLR, MultiStepLR, ReduceLROnPlateau

# Parameters specific to CosineAnnealingLR
cosine_T_max:
  value: 10
cosine_eta_min:
  value: 0
# Parameters specific to ReduceLROnPlateau
reduce_factor:
  value: 0.5
reduce_patience:
  value: 10
# Parameters specific to MultiStepLR
multistep_milestones:
  value: [30, 60, 90]
multistep_gamma:
  value: 0.5

# Warmup Epochs
warmup_epochs:
  value: 0

# Optimizer Parameters
weight_decay:
  value: 0.01
beta1:
  value: 0.9
beta2:
  value: 0.999

# Other training parameters
log_freq:
  value: 5
val_freq:
  value: 5
  
# Test options
saved_checkpoint:
  value: None

  # copper-sweep-1 ('learning_rate': 0.0001, 'lr_scheduler': 'CosineAnnealingLR', 'warmup_epochs': 0, 'patch_size': 112)
  #value: "/home/guests/jorge_padilla/output/models/DynamicPET_Segmentation/checkpoints/copper-sweep-1/epoch=129-step=65780.ckpt"

  # polar-water-25 ('learning_rate': 0.0001, 'lr_scheduler': 'MultiStepLR', 'warmup_epochs': 0, 'patch_size': 112)
  #value: "/home/guests/jorge_padilla/output/models/DynamicPET_Segmentation/checkpoints/polar-water-25/epoch=94-step=14250.ckpt"

  # spring-cherry-204 ('learning_rate': 0.0001, 'lr_scheduler': 'CosineAnnealingLR', 'warmup_epochs': 0, 'patch_size': Full Volume per slices, 'dataset': 'P512 - Full Volume per slices'
  #value: "/home/guests/jorge_padilla/output/models/DynamicPET_Segmentation/checkpoints/spring-cherry-204/epoch=19-step=85000.ckpt"