modality: 
  value: "train" # "test", "train", "grid_search"

# Architecture
use_spatio_temporal_unet: #Convolution:: true -> Spatio-temporal, false -> 3D
  value: True

model_depth:
  value: 4

max_pool_time: #Pooling:: true -> 3D, false -> Space
  value: True

final_activation: #Final activation:: multi_clamp, clamp, absolute
  value: "multi_clamp" 

activation:
  value:  "ELU"

patch_size:
  value: 184

  # Trials
  # 128: Works
  # 112 Original
  # 224 Out of memory (Run 2253)
  
# Dataset
patient_list:
  value:  {
          "train": ["01", "07", "06", "10", "15", "19", "21", "23", "27", "29"],  
          "validation": ["01", "14", "16", "17", "18"], 
          "test": ["28", "28", "08", "09", "20", "24", "25", "26", "03"]
        }

slices_per_patient_train:         # Should be "None" or "all" if all the slices must be included
  value: "all"

slices_per_patient_val:
  value: "all"

slices_per_patient_test:
  value: "all"

# Training options
epochs: 
  value: 500

continue_checkpoint:
  value: ""

batch_norm: 
  desc: Use of batch normalization
  value: False

learning_rate:
  value: 0.0001 

lr_scheduler:
  value: "CosineAnnealingLR"

warmup_epochs:
  value: 0

batch_size: 
  desc: Training and validation batch size
  value: 5

# Logging
log_freq:
  value: 5

val_freq:
  value: 5
  
# Test
saved_checkpoint:
  # copper-sweep-1 ('learning_rate': 0.0001, 'lr_scheduler': 'CosineAnnealingLR', 'warmup_epochs': 0, 'patch_size': 112)
  value: "/home/guests/jorge_padilla/output/models/DynamicPET_Segmentation/checkpoints/copper-sweep-1/epoch=129-step=65780.ckpt"

  # polar-water-25 ('learning_rate': 0.0001, 'lr_scheduler': 'MultiStepLR', 'warmup_epochs': 0, 'patch_size': 112)
  #value: "/home/guests/jorge_padilla/output/models/DynamicPET_Segmentation/checkpoints/polar-water-25/epoch=94-step=14250.ckpt"
