experiment:
  value: "kinetics"

use_spatio_temporal_unet: #Convolution:: true -> Spatio-temporal, false -> 3D
  value: True

remove_slices_without_segmentation:
  value: False

batch_size: 
  value: 6

monitor_metric:
  value: "val_loss_kinetics"

val_freq:
  value: 5

learning_rate:
  value: 0.0001 

batch_norm: 
  value: False

dropout:
  value: 0.3

init_weights:
  value: None # Options: kaiming, xavier, None