experiment:
  value: "adaptation3"

freeze_kin:
  value: False

alternate_training:
  value: True
  
loss_combination:
  value: "weighted_sum"

rescaling_factor_kinetic_loss:
  value: 1000

remove_slices_without_segmentation:
  value: False

inverse_segmentations:
  value: False

batch_size: 
  value: 4

segmentation_list:
  value: ["liver", "kidneys", "vessels", "aorta"]

monitor_metric:
  value: "val_loss_segmentation"