experiment:
  value: "segmentation"

segmentation_network:
  value: "UNet" # Options: "UNet", "SegResNetDS"

dropout:
  value: 0

dropout_seg:
  value: 0.1

batch_size: 
  value: 16

segmentation_list:
  value: ["liver", "kidneys", "vessels", "aorta"]

remove_slices_without_segmentation:
  value: False

monitor_metric:
  value: "val_loss_segmentation"

val_freq:
  value: 3

inverse_segmentations:
  value: False